SELECT 
FLAN.CODFILIAL as FILIAL, 
FLAN.NUMERODOCUMENTO, 
FLAN.PARCELA, 
FLAN.CODTDO AS TIPO, 
FLAN.CODCAIXA AS CONTA_CAIXA, 
FLAN.DATAEMISSAO, 
FLAN.DATADIGITACAO, 
FLAN.DATAPREVBAIXA, 
FLAN.DATAVENCIMENTO, 
FLAN.DATABAIXA, 
FLAN.VALORORIGINAL,
FLAN.VALORJUROS,
FLAN.VALORDESCONTO,
FLAN.VALOROP1 AS OUTROS_ACRESCIMOS, 
FLAN.VALORBAIXADO,  
FLAN.CCUSTO, 
FCCUSTO.DESCRICAO, 
FCFO.CODCFO, 
FCFO.NOME, 
FLAN.HISTORICO FROM FLAN
LEFT JOIN FCFO ON FLAN.CODCFO = FCFO.CODCFO
LEFT JOIN FCCUSTO ON FLAN.CCUSTO = FCCUSTO.COD
WHERE DATAVENCIMENTO BETWEEN ? AND ?
--AND FLAN.STATUSLAN <> 'C'
AND FLAN.STATUSLAN = 'A'
AND FLAN.PAGREC = 'P'
AND FLAN.CODTDO <> 'PRE'
ORDER BY FLAN.DATAVENCIMENTO ASC
