SELECT 
    -- Dados da Movimentação Atual (NF/Saída)
    T1.IDMOV,
    T1.CODTMV,
    T1.NUMEROMOV AS NUMERO_DOC,
    T1.DATAEMISSAO,
    
    
    -- Dados do Cliente/Fornecedor (A junção que você solicitou)
    F_CLIENTE.CODCFO,
    F_CLIENTE.NOME AS NOME_CLIENTE,
    F_CLIENTE.NOMEFANTASIA AS FAN_CLIENTE,
    F_CLIENTE.CIDADE,
    T1.CAMPOLIVRE1 AS OBRA,
    
    -- Dados do Produto
    P.CODPRD,
    P.NOMEFANTASIA AS PRODUTO,
    P.NUMNOFABRIC,
    P.UNIDADE,
    
    -- Itens e Valores
    IT.QUANTIDADE,
    --IT.VALORUNITARIO,
    IT.PRECOUNITARIO,
    IT.VALORTOTALITEM,
    
    -- Dados do Movimento de Origem (Ex: Pedido)
    T2.NUMEROMOV AS PEDIDO_ORIGEM,
    F_ORIGEM.NOME AS FORNECEDOR_ORIGEM
    
FROM TMOVITENS IT
LEFT JOIN TMOV T1 ON 
    (T1.CODEMPRESA = IT.CODEMPRESA AND T1.IDMOV = IT.IDMOV)
LEFT OUTER JOIN TPRODUTO P ON 
    (P.CODEMPRESA = IT.CODEMPRESA AND P.CODPRD = IT.CODPRD)
LEFT OUTER JOIN FCFO F_CLIENTE ON 
    (F_CLIENTE.CODEMPRESA = T1.CODEMPRESA AND F_CLIENTE.CODCFO = T1.CODCFO) -- Junção solicitada
LEFT OUTER JOIN TMOV T2 ON 
    (T2.CODEMPRESA = T1.CODEMPRESA AND T2.IDMOV = T1.IDMOVRELAC)
LEFT OUTER JOIN FCFO F_ORIGEM ON 
    (F_ORIGEM.CODEMPRESA = T2.CODEMPRESA AND F_ORIGEM.CODCFO = T2.CODCFO)
WHERE 
    T1.CODTMV IN ('2.2.10', '2.2.24', '1.2.17')
    AND T1.DATAEMISSAO between ? and ?
    AND T1.STATUS <> 'C'
    AND T2.NUMEROMOV = ?
    AND T2.SERIE = ?
    AND T2.CODFILIAL = '1'
ORDER BY 
    T1.VALORLIQUIDO DESC;
